export const TOPBAR_ICON_BUTTON_CLASS_NAME = [
  "relative flex h-[42px] w-[42px] items-center justify-center",
  "rounded-[13px]",
  "border border-topbar-border/80",
  "bg-topbar-surface/80",
  "text-topbar-foreground",
  "backdrop-blur-xl",
  "transition-all duration-200",
  "hover:-translate-y-0.5",
  "hover:bg-topbar-soft",
  "hover:shadow-sm",
  "focus-visible:outline-none",
  "focus-visible:ring-2",
  "focus-visible:ring-ring",
  "motion-reduce:transform-none",
].join(" ");