import { Eye } from "lucide-react";
import { Button } from "@/shared/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/shared/ui/table";
import type { Installment } from "../../types/finance.types";
import { financeIconButton } from "../shared/FinancePrimitives";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n||0);
const date=(v:string)=>v?new Intl.DateTimeFormat("en-US",{year:"numeric",month:"short",day:"2-digit"}).format(new Date(v)):"—";
export function InstallmentsTable({installments,onView}:{installments:Installment[];onView?:(id:string|number)=>void}){
 if(!installments.length)return <div className="rounded-[22px] border border-dashed border-border bg-card p-12 text-center"><h3 className="font-semibold">No student installments found</h3><p className="mt-2 text-sm text-muted-foreground">Installments appear after a student financial contract is finalized.</p></div>;
 return <div className="overflow-hidden rounded-[22px] border border-border/70 bg-card shadow-[0_12px_30px_rgba(31,25,78,0.055)]"><Table><TableHeader><TableRow className="h-12 border-border/65 bg-muted/35 hover:bg-muted/35"><TableHead>STUDENT INSTALLMENT</TableHead><TableHead>AMOUNT DUE</TableHead><TableHead>AMOUNT PAID</TableHead><TableHead>DUE DATE</TableHead><TableHead>STATUS</TableHead><TableHead className="text-right">ACTIONS</TableHead></TableRow></TableHeader><TableBody>{installments.map(item=><TableRow key={item.id} className="min-h-16 border-border/55 hover:bg-primary/[0.025]"><TableCell className="font-semibold text-foreground">{item.title}<span className="ml-2 text-xs font-normal text-muted-foreground">#{item.installmentNumber||"—"}</span></TableCell><TableCell>{money(item.amountDue)}</TableCell><TableCell className="font-semibold text-success">{money(item.amountPaid)}</TableCell><TableCell>{date(item.dueDate)}</TableCell><TableCell><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${item.status==="paid"?"bg-success/12 text-success":item.status==="overdue"?"bg-destructive/10 text-destructive":"bg-info/10 text-info"}`}>{item.status.replaceAll("_"," ")}</span></TableCell><TableCell className="text-right"><Button variant="outline" size="icon" className={financeIconButton} onClick={()=>onView?.(item.id)} aria-label="View installment"><Eye className="h-4 w-4"/></Button></TableCell></TableRow>)}</TableBody></Table></div>;
}
