import { useQuery } from "@tanstack/react-query";
import { Printer, ReceiptText } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/shared/ui/dialog";
import { Button } from "@/shared/ui/button";
import { financeOperationsService } from "../../services/finance-operations.service";

type Props = { open: boolean; onOpenChange: (open: boolean) => void; paymentId: string | number | null };

const formatMethod = (method: string) => ({ cash: "Cash", bank_transfer: "Bank Transfer", cheque: "Cheque", electronic_wallet: "E-Wallet" }[method] ?? method);

function ReceiptSkeleton() {
  return <div className="space-y-4 py-2">{["h-20","h-12","h-12","h-12","h-12"].map((h,i)=><div key={i} className={`${h} animate-pulse rounded-[15px] bg-muted/65`} />)}</div>;
}

export function PaymentReceiptDialog({ open, onOpenChange, paymentId }: Props) {
  const { data: receipt, isLoading, isError } = useQuery({
    queryKey: ["payment-details", paymentId],
    queryFn: () => financeOperationsService.getPaymentDetails(paymentId!),
    enabled: !!paymentId && open,
  });

  function printReceipt() {
    if (!receipt) return;
    const win = window.open("", "_blank", "width=900,height=900");
    if (!win) return;
    win.document.write(`<!doctype html><html><head><title>Receipt #${receipt.id}</title><style>
      *{box-sizing:border-box} body{margin:0;background:#f5f5f7;font-family:Arial,sans-serif;color:#20202a}.sheet{width:210mm;min-height:297mm;margin:0 auto;background:white;padding:22mm}.top{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #ece9f8;padding-bottom:18px}.brand{font-size:24px;font-weight:600}.muted{color:#77758a;font-size:12px}.receipt-title{font-size:15px;font-weight:600;text-transform:uppercase;letter-spacing:.12em;color:#6758d4}.amount{margin:28px 0;padding:22px;border:1px solid #e8e4f6;border-radius:16px;background:#faf9ff;text-align:center}.amount strong{font-size:34px;font-weight:600;color:#5547bf}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.item{padding:14px 16px;border-bottom:1px solid #ececf2}.item span{display:block;font-size:11px;color:#858399;margin-bottom:6px}.item b{font-size:14px;font-weight:500}.footer{margin-top:42px;display:flex;justify-content:space-between;align-items:flex-end}.signature{width:180px;border-top:1px solid #aaa;padding-top:8px;text-align:center;font-size:11px;color:#777}@media print{body{background:white}.sheet{margin:0;width:auto;min-height:auto;box-shadow:none}}</style></head><body><main class="sheet"><div class="top"><div><div class="brand">School Finance Office</div><div class="muted">Official student payment receipt</div></div><div><div class="receipt-title">Payment Receipt</div><div class="muted">Receipt #${receipt.id}</div></div></div><div class="amount"><div class="muted">Amount received</div><strong>${receipt.paidAmount?.toLocaleString()} $</strong></div><div class="grid"><div class="item"><span>Payment date</span><b>${receipt.paymentDate || "N/A"}</b></div><div class="item"><span>Payment method</span><b>${formatMethod(receipt.paymentMethod)}</b></div><div class="item"><span>Paper reference</span><b>${receipt.paperReceiptNo || "—"}</b></div><div class="item"><span>Digital reference</span><b>${receipt.digitalReference || "—"}</b></div><div class="item"><span>Processed by</span><b>${receipt.cashierName || "System Admin"}</b></div><div class="item"><span>Status</span><b>Payment received</b></div></div><div class="footer"><div class="muted">Generated by the school management system</div><div class="signature">Authorized signature</div></div></main><script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}</script></body></html>`);
    win.document.close();
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="overflow-hidden rounded-[22px] border-border/55 p-0 sm:max-w-[480px]">
        <DialogHeader className="border-b border-border/45 px-6 py-5 text-left">
          <div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-[14px] border border-primary/18 bg-primary/[0.07] text-primary"><ReceiptText className="h-[18px] w-[18px]" strokeWidth={1.8}/></div><DialogTitle className="text-[17px] font-medium tracking-[-0.015em] text-foreground/90">Payment receipt</DialogTitle></div>
        </DialogHeader>
        <div className="p-6">
          {isLoading ? <ReceiptSkeleton/> : isError || !receipt ? <div className="rounded-[16px] border border-destructive/18 bg-destructive/[0.045] px-4 py-8 text-center text-[13px] text-destructive">Unable to load receipt details.</div> : <div className="space-y-5"><div className="rounded-[18px] border border-primary/14 bg-primary/[0.045] px-5 py-5 text-center"><p className="text-[11.5px] font-normal uppercase tracking-[0.08em] text-muted-foreground">Amount received</p><p className="mt-1 text-[28px] font-medium tracking-[-0.025em] text-primary">{receipt.paidAmount?.toLocaleString()} $</p><span className="mt-2 inline-flex rounded-full border border-success/18 bg-success/10 px-2.5 py-1 text-[11px] font-medium text-success">Payment successful</span></div><div className="divide-y divide-border/35 rounded-[16px] border border-border/45 px-4">{[["Receipt ID",`#${receipt.id}`],["Payment date",receipt.paymentDate || "N/A"],["Payment method",formatMethod(receipt.paymentMethod)],["Reference",receipt.paperReceiptNo || receipt.digitalReference || "—"],["Processed by",receipt.cashierName || "System Admin"]].map(([label,value])=><div key={label} className="flex items-center justify-between gap-4 py-3.5"><span className="text-[12.5px] font-normal text-muted-foreground">{label}</span><span className="text-right text-[12.5px] font-medium text-foreground/84">{value}</span></div>)}</div><Button onClick={printReceipt} className="h-10 w-full rounded-xl text-[12.5px] font-medium"><Printer className="mr-2 h-4 w-4" strokeWidth={1.8}/>Print receipt</Button></div>}
        </div>
      </DialogContent>
    </Dialog>
  );
}
