import { Edit2, Eye, Trash2 } from "lucide-react";
import { Button } from "@/shared/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/shared/ui/table";
import type { PaymentReceipt } from "../../types/finance.types";
import { financeDeleteIconButton, financeIconButton } from "../shared/FinancePrimitives";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n||0);
const method=(v:string)=>({cash:"Cash",bank_transfer:"Bank Transfer",cheque:"Cheque",electronic_wallet:"E-Wallet"}[v]??v);
export function PaymentsTable({payments,onView,onEdit,onDelete}:{payments:PaymentReceipt[];onView?:(id:string|number)=>void;onEdit?:(payment:PaymentReceipt)=>void;onDelete?:(id:string|number)=>void}){
 if(!payments.length)return <div className="rounded-[22px] border border-dashed border-border bg-card p-12 text-center"><h3 className="font-semibold">No student payments found</h3><p className="mt-2 text-sm text-muted-foreground">Use Process Payment to record the first student receipt.</p></div>;
 return <div className="overflow-hidden rounded-[22px] border border-border/70 bg-card shadow-[0_12px_30px_rgba(31,25,78,0.055)]"><Table><TableHeader><TableRow className="h-12 border-border/65 bg-muted/35 hover:bg-muted/35"><TableHead>RECEIPT</TableHead><TableHead>AMOUNT</TableHead><TableHead>METHOD</TableHead><TableHead>REFERENCE</TableHead><TableHead>DATE</TableHead><TableHead className="text-right">ACTIONS</TableHead></TableRow></TableHeader><TableBody>{payments.map(p=><TableRow key={p.id} className="border-border/55 hover:bg-primary/[0.025]"><TableCell className="font-semibold">#{p.id}</TableCell><TableCell className="font-bold text-success">{money(p.paidAmount)}</TableCell><TableCell><span className="rounded-full bg-info/10 px-3 py-1.5 text-xs font-semibold text-info">{method(p.paymentMethod)}</span></TableCell><TableCell className="text-muted-foreground">{p.paperReceiptNo||p.digitalReference||"—"}</TableCell><TableCell>{p.paymentDate?new Date(p.paymentDate).toLocaleDateString():"—"}</TableCell><TableCell><div className="flex justify-end gap-2"><Button variant="outline" size="icon" className={financeIconButton} onClick={()=>onView?.(p.id)}><Eye className="h-4 w-4"/></Button><Button variant="outline" size="icon" className={financeIconButton} onClick={()=>onEdit?.(p)}><Edit2 className="h-4 w-4"/></Button><Button variant="outline" size="icon" className={financeDeleteIconButton} onClick={()=>onDelete?.(p.id)}><Trash2 className="h-4 w-4"/></Button></div></TableCell></TableRow>)}</TableBody></Table></div>;
}
